MOB-2516 [Publish Release 1.0.1]
karhoo/KarhooPods pull request #3
Opened 2020-03-13 16:02 UTC by JeevanThandi

2020-03-13 16:05 UTC, mohadian requested changes

2020-03-13 16:05 UTC, mohadian commented on KarhooSDK.podspec
> +  s.license               = 'BDS-2'
I think it should be `BSD-2-Clause`

2020-03-13 16:05 UTC, mohadian commented on KarhooSDK/1.0.1/KarhooSDK.podspec
> +  s.author                = { "Karhoo" => "ios@karhoo.com" }
Is the email correct? Do we check this email?

2020-03-13 16:07 UTC, Tbruni85 submitted a review, later dismissed
![](https://media.giphy.com/media/Dsr9bhYs0PXry/giphy.gif)

2020-03-13 16:08 UTC, mohadian commented
![](https://media.giphy.com/media/MUEq7KfQvNolX9YujV/giphy.gif)

2020-03-15 00:04 UTC, mohadian approved these changes

2020-03-16 18:22 UTC, merged